### ISSUE TITLE
Hardcoded "SONG" song in MusicController.

### ISSUE THREAD

**Issue by paskausks** [R3X-G1L6AME5H/godot-dynamic-music-framework#1]
First of all, very happy with having found this library, and hope that it will see further development some time - perhaps, for Godot 4!

I have a minor complaint - there's a hardcoded `DMFSong` "SONG" set to start on `MusicController` startup, which forces the library user to define a node with that name, and if they don't need the song to play right away, they'd need to stop it, which seemingly isn't currently possible.

See here: https://github.com/R3X-G1L6AME5H/godot-dynamic-music-framework/blob/678f40232859dc8ae270fab9e63c0527f192784e/addons/DMF/singletons/MusicController.gd#L59

**Comment by R3X-G1L6AME5H** [comment]
Cheers for raising the issue :smile:. That was a leftover debug line :thinking:. I say WAS because it turns out I commented it out a while ago in [this](https://github.com/R3X-G1L6AME5H/godot-dynamic-music-framework/commit/78e364229007869981b9114bfb691d78df7e6135#diff-d8138b1ea8eb30ce33b7761188122270e3ec9dc0bfc1c2d9090aab1269d07815L59) commit. Therefore this issue is rather posthumosly closed.

As per late response... no excuse, shame on me :blush:.
